In [5]:
from numpy import *
random.rand(4, 4)


array([[0.42840239, 0.11332206, 0.73258979],
       [0.80125263, 0.57752112, 0.8453534 ],
       [0.86191157, 0.93060458, 0.83092907]])

In [9]:
randomMat = mat(random.rand(3, 3))
randomMat

matrix([[0.70160885, 0.58187665, 0.11785208],
        [0.89197875, 0.05190234, 0.85582884],
        [0.94853443, 0.88519592, 0.72876329]])

In [11]:
randomMat.I * randomMat

matrix([[ 1.00000000e+00,  2.22044605e-16,  2.22044605e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [-2.22044605e-16,  0.00000000e+00,  1.00000000e+00]])

In [12]:
eye(4)

ey

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])